import Link from 'next/link';

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-black py-12 px-4">
            <div className="max-w-3xl mx-auto">
                <Link href="/" className="text-cyan-400 hover:text-cyan-300 mb-8 inline-block">
                    ← Back to Home
                </Link>

                <h1 className="text-3xl font-bold neon-text-cyan mb-2">Terms of Service</h1>
                <p className="text-gray-500 text-sm mb-8">Last Updated: January 14, 2026</p>

                <div className="prose prose-invert max-w-none space-y-6">
                    <p className="text-gray-300">
                        Welcome to EtchVox. By accessing or using our website and services, you agree to be bound by
                        these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use our services.
                    </p>

                    <h2 className="text-xl font-bold text-cyan-400 mt-8 mb-4">1. Age Requirement & Service Access</h2>
                    <p className="text-gray-300">
                        You must be at least 13 years old (or the age of majority in your jurisdiction) to use this Service.
                        The content generated by EtchVox includes sharp tongue, sarcasm, and potentially offensive remarks.
                        By using this service, you acknowledge that this is for <strong>ENTERTAINMENT PURPOSES ONLY</strong> and
                        agree not to hold us liable for any outcomes caused by the results.
                    </p>
                    <div className="bg-red-500/10 border-l-4 border-red-500 p-4 my-4">
                        <strong className="text-red-400">⚠️ MATURE CONTENT WARNING</strong>
                        <p className="text-gray-400 mt-2">
                            The Service contains mature themes and sharp language. Users who are sensitive to criticism or
                            offensive commentary should not utilize the AI Roast features.
                        </p>
                    </div>

                    <h2 className="text-xl font-bold text-cyan-400 mt-8 mb-4">2. User Conduct & Voice Data</h2>
                    <p className="text-gray-300">
                        You represent and warrant that you own the rights to the audio files you upload or have obtained
                        explicit permission from the speaker. You agree not to upload voice data of third parties without
                        their consent. We reserve the right to ban users who upload illegal, hateful, or unauthorized content.
                    </p>

                    <h2 className="text-xl font-bold text-cyan-400 mt-8 mb-4">3. Support and Access</h2>
                    <ul className="text-gray-300 list-disc list-inside space-y-2">
                        <li><strong>Support Levels:</strong> Premium features are available as a "coffee" support starting from $5.00 USD as indicated.</li>
                        <li><strong>Payment Processing:</strong> Payments are processed via Buy Me a Coffee. We do not store your credit card information.</li>
                    </ul>
                    <div className="bg-red-500/10 border-l-4 border-red-500 p-4 my-4">
                        <strong className="text-red-400">NO REFUNDS</strong>
                        <p className="text-gray-400 mt-2">
                            Due to the nature of digital content, <strong>ALL SALES ARE FINAL</strong>. Once the AI generation
                            process has started, we cannot offer a refund, exchange, or cancellation.
                        </p>
                    </div>

                    <h2 className="text-xl font-bold text-cyan-400 mt-8 mb-4">4. Disclaimer of Warranties</h2>
                    <p className="text-gray-300">
                        EtchVox is provided "as is" without any guarantees. The personality insights and analysis are
                        generated by Artificial Intelligence and <strong>should not be considered as psychological, medical,
                            or professional advice</strong>. We make no claims regarding the scientific accuracy of the results.
                    </p>

                    <h2 className="text-xl font-bold text-cyan-400 mt-8 mb-4">5. Intellectual Property & Data Rights</h2>
                    <p className="text-gray-300">
                        You retain ownership of your original voice recordings. By using the service, you grant
                        EtchVox a worldwide, non-exclusive license to process your audio for report generation.
                        <strong>AI Research and algorithm improvement</strong> are performed only upon receiving your explicit
                        opt-in consent during the recording sequence.
                    </p>

                    <h2 className="text-xl font-bold text-cyan-400 mt-8 mb-4">6. Data Deletion & Sovereignty</h2>
                    <p className="text-gray-300">
                        Users can archive data to hide it from their active view. For permanent deletion requests compliant with GDPR/CCPA, please contact support. Anonymized acoustic vectors may be retained for system optimization as detailed in the Privacy Policy.
                    </p>

                    <h2 className="text-xl font-bold text-cyan-400 mt-8 mb-4">7. Limitation of Liability</h2>
                    <p className="text-gray-300">
                        To the fullest extent permitted by law, EtchVox and its operators shall not be liable for any
                        indirect, incidental, or consequential damages arising out of your use of the service, including
                        but not limited to: failed relationships, damaged professional reputations, emotional distress,
                        missed opportunities, or any other personal, social, or professional outcomes.
                    </p>

                    <h2 className="text-xl font-bold text-cyan-400 mt-8 mb-4">8. Governing Law</h2>
                    <p className="text-gray-300">
                        These Terms shall be governed by and construed in accordance with the laws of Japan. Any disputes
                        arising from these Terms shall be subject to the exclusive jurisdiction of the Tokyo District Court.
                    </p>

                    <h2 className="text-xl font-bold text-cyan-400 mt-8 mb-4">9. Contact</h2>
                    <p className="text-gray-300">
                        Questions? Contact us at: <a href="mailto:info@etchvox.com" className="text-cyan-400 hover:underline">info@etchvox.com</a>
                    </p>
                </div>
            </div>
        </div>
    );
}
